package com.mini.model;
// Generated 17-04-2016 20:22:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="minimarket3"
)
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Tipoproducto tipoproducto;
     private String nombreProducto;
     private String descripccion;
     private int valor;
     private int stock;
     private int dsct;
     private int codigo;

    public Producto() {
    }

	
    public Producto(Tipoproducto tipoproducto, String nombreProducto, int valor, int stock, int dsct, int codigo) {
        this.tipoproducto = tipoproducto;
        this.nombreProducto = nombreProducto;
        this.valor = valor;
        this.stock = stock;
        this.dsct = dsct;
        this.codigo = codigo;
    }
    public Producto(Tipoproducto tipoproducto, String nombreProducto, String descripccion, int valor, int stock, int dsct, int codigo) {
       this.tipoproducto = tipoproducto;
       this.nombreProducto = nombreProducto;
       this.descripccion = descripccion;
       this.valor = valor;
       this.stock = stock;
       this.dsct = dsct;
       this.codigo = codigo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProducto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TipoProducto_idTipoProducto", nullable=false)
    public Tipoproducto getTipoproducto() {
        return this.tipoproducto;
    }
    
    public void setTipoproducto(Tipoproducto tipoproducto) {
        this.tipoproducto = tipoproducto;
    }

    
    @Column(name="nombreProducto", nullable=false, length=50)
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    
    @Column(name="descripccion", length=100)
    public String getDescripccion() {
        return this.descripccion;
    }
    
    public void setDescripccion(String descripccion) {
        this.descripccion = descripccion;
    }

    
    @Column(name="valor", nullable=false)
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }

    
    @Column(name="stock", nullable=false)
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }

    
    @Column(name="dsct", nullable=false)
    public int getDsct() {
        return this.dsct;
    }
    
    public void setDsct(int dsct) {
        this.dsct = dsct;
    }

    
    @Column(name="Codigo", nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }




}


