package com.mini.model;
// Generated 17-04-2016 20:22:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoproducto generated by hbm2java
 */
@Entity
@Table(name="tipoproducto"
    ,catalog="minimarket3"
)
public class Tipoproducto  implements java.io.Serializable {


     private Integer idTipoProducto;
     private String nombreTipo;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Tipoproducto() {
    }

	
    public Tipoproducto(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Tipoproducto(String nombreTipo, Set<Producto> productos) {
       this.nombreTipo = nombreTipo;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTipoProducto", unique=true, nullable=false)
    public Integer getIdTipoProducto() {
        return this.idTipoProducto;
    }
    
    public void setIdTipoProducto(Integer idTipoProducto) {
        this.idTipoProducto = idTipoProducto;
    }

    
    @Column(name="nombreTipo", nullable=false, length=45)
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoproducto")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


